sudo: required
services:
  - docker

before_install:
  - docker build -t alexandrumogic/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alexandrumogic/docker-react npm run test -- --coverage
